### PR TITLE
added espresso++ to the software list

### PR DESCRIPTION
**Pull request by jkrajniak**

### CODE REVIEW

**Comment by pdebuyl** [comment]
Hi Jakub,

Thanks for the PR :-) I merge now but I need to get the publishing scripts to work again to publish :-/ I'll update you when the website is updated.

**Comment by pdebuyl** [comment]
Actually, I leave the PR open as a reminder to publish.

**Comment by fhoefling** [comment]
@pdebuyl `make upload` did the trick - just (re-)discovered

**Comment by pdebuyl** [comment]
Thanks @fhoefling ! I had an issue with a "too recent" sphinx w.r.t. what the script does I believe... I should update the scripts acoordingly.

**Pull request merged**
